server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/proposal_db
spring.datasource.username=postgres
spring.datasource.password=abc123def
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
server.servlet.session.timeout=10m
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
recaptcha.secret=6Ldiyj8tAAAAABmS6Sjut6qivePXmCwbjHpELG9p